
services:
  mysql:
    image: mysql:latest
    container_name: mysql_ml
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ml_model
      MYSQL_USER: akshu
      MYSQL_PASSWORD: karan
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8082:80"

volumes:
  mysql_data:
